### ISSUE TITLE
tabular sarsa update

### ISSUE THREAD

**Issue by henrycharlesworth** [mcmachado/count_based_exploration_sr#1]
Hi, just checking for my own sanity: in both tabular/sarsa_agent.py and tabular/sarsa_sr_agent.py you use the following to update q:

def update_q_values(self, s, a, r, next_s, next_a):
        self.q[s][a] = self.q[s][a] + self.alpha * (r + self.gamma - (1.0 - self.env.is_terminal()) *
self.q[next_s][next_a] - self.q[s][a])

why is it r + self.gamma - (1.0-terminal)*q[next_s][next_a] ... rather than r + self.gamma*(1.0-terminal)*q[next_s][next_a] ?
you do the same with the SR update. This is a mistake, right? (I can see it might not effect the results too much, but I just wanted to check!)

**Comment by mcmachado** [comment]
Good catch, @henrycharlesworth ! Thanks for that. It seems you are correct.
I'll need to fine tune the parameters again for both Sarsa+SR and Sarsa in RiverSwim and SixArms. The parameters I report in the paper are not that effective. I'll be pushing a fix soon.

**Comment by mcmachado** [comment]
I fixed this issue in my last commit. This bug does change the results reported in the paper (I'll make sure to update it on arXiv soon). For the record, now when we run the code this is what we have (standard deviation over 100 runs is reported between parentheses):

### **Riverswim**
- **Sarsa+SR w/ L1-norm**: _1,213,544.1 (540,453.8)_
_`[ step_size: 0.25 ; gamma(sr): 0.95 ; step_size(sr): 0.01 ; beta: 100 ; epsilon: 0.1 ]`_
- **Sarsa+SR w/ L2-norm**: _1,192,052.4 (507,178.5)_
_`[ step_size: 0.25 ; gamma(sr): 0.99 ; step_size(sr): 0.01 ; beta: 100 ; epsilon: 0.1 ]`_
- **Sarsa**:  _24,769.85 (196.1)_
_`[ step_size: 0.005 ; epsilon: 0.01 ]`_


### **SixArms**
- **Sarsa+SR w/ L1-norm**: _1,052,933.8 (2,311,616.8)_
_`[ step_size: 0.1 ; gamma(sr): 0.99 ; step_size(sr): 0.01 ; beta: 100 ; epsilon: 0.01 ]`_
- **Sarsa+SR w/ L2-norm**: _819,926.7 (2,132,002.9)_
_`[ step_size: 0.1 ; gamma(sr): 0.99 ; step_size(sr): 0.01 ; beta: 10 ; epsilon: 0.01 ]`_
- **Sarsa**:  _247,977.1 (4,969.5)_
_`[ step_size: 0.465 ; epsilon: 0.03 ]`_

### **Conclusion**

In summary, the general message of the paper doesn't change with the new results. Using the SR as an exploration bonus even in the tabular case drastically improves the performance of RL agents in RiverSwim and SixArms. Surprisingly, there was a considerable drop in performance though. It is interesting to understand why the introduced bug generated such a good result (it is equivalent of using `gamma = 1` and an additional bonus on the reward signal). Finally, in these domains, using the L2-norm of the SR leads to worse performance than when using the L1-norm of the SR. This is the only change from the conclusions currently present in the paper.

I really appreciate the fact that you took the time to read my code and reach out telling me about the bug. Hopefully this answers your question.
